shell /bin/zsh

# BEGIN_KITTY_FONTS Monaco
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 17
background_opacity 0.91
background_blur 16
# END_KITTY_FONTS

# WINDOW
window_padding_width 8
confirm_os_window_close 0

enabled_layouts tall:bias=80;full_size=1;mirrored=false

# TAB BAR
tab_bar_style separator
tab_bar_edge top
tab_separator " "

# TITLE BAR
hide_window_decorations titlebar-only

# OS
macos_option_as_alt both


# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME
